language: php

sudo: false

services:
  - docker

php:
  - 7.4

jobs:
  include:
    - stage: build docker image
      if: tag IS present
      php: 7.4
      env: COMPOSER_FLAGS=""
      script:
        - rm -rf vendor/
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - export REPO=$DOCKER_USERNAME/phpinsights
        - docker build -f docker/Dockerfile -t $REPO:$TRAVIS_TAG .
        - docker tag $REPO:$TRAVIS_TAG $REPO:latest
        - docker push $REPO:$TRAVIS_TAG
        - docker push $REPO:latest
